### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by vasylskorych** [FlowsheetSimulation/Dyssol-open#1]
Update documentation for all new classes and unit development.
Possibly transfer everything from pdf files to Wiki

**Comment by gladk** [comment]
Just an opinion on this issue. From my experience, I would better propose to use write the documentation as the part of the code. The documentation can be easily generated by pipelines (GitHub action) and uploaded on the website.

Wiki is also OK, but usually it is getting fast outdated, and you do not have a control about content of the Wiki. If the documentation is in the source code, you can see, (in pull request or directly in the commit) what was changed.

As a tool - sphinx should work very well. If you want - I can prepare the skeleton for the initial doc generation, just to check the concept, whether it is suitable for this project.

**Comment by vasylskorych** [comment]
It's a good point, I agree. 
My idea was to use the infrastructure of GitHub to host the documentation, and it seems that GitHub-Pages are able to work sphinx-generated docs: https://daler.github.io/sphinxdoc-test/includeme.html
In addition to dimanically generated API-documentaion from code (what is now under Development/Program Interfaces/*.pdf) we also need to have a 'static' part with the description of GUI, methods, units and so on (the rest of the docs). Just don't know how easy it is to couple these two via GitHub action, but I guess it should be possible.
We do already have a static part of the documentation in sphinx, so we can take it
https://github.com/lizardzhou/Dyssol

**Comment by gladk** [comment]
I guess it can be closed?
