### ISSUE TITLE
GUI does not read out correct AddConstIntParameter initial value

### ISSUE THREAD

**Issue by Selene29** [FlowsheetSimulation/Dyssol-open#183]
```
void CTest::CreateStructure()
{
	AddConstIntParameter("TestInt", 4, "-", "abc", 3, 10);
}
```

Parameter gets set correctly in the background, but the UI displays always 1 instead of 4.

version: current master

**Comment by vasylskorych** [comment]
Here, "4" is an initial value, and you should see it if you add a new model on the flowsheet. The observed behaviour can happen if, you open an old flowsheet with an old version of this model, where a parameter (maybe even with other name) on its place had value of "1". Could you confirm that "1" is displayed even for a new added units?
