### ISSUE TITLE
Error in IDASolve, residual function failed

### ISSUE THREAD

**Issue by HannesWeska** [FlowsheetSimulation/Dyssol-open#44]
I'm getting the same error for two different flowsheets ("Abschnitt_3.dflw" & "Abschnitt_4.dflw"). The Only difference is the Timepoint at wich it happens. The error occurred after I added the last Timedelay to each flowsheet (Abschnitt_3: "Zeitversatz 03 Nr 20 zu Nr 29"; Abschnitt_4: "Zeitversatz 03 Nr 1.15").
There are two more flowsheets ("Abschnitt_3_ohne_zeitversatz.dflw" & "Abschnitt_4_ohne_zeitversatz.dflw"). Here I left out the last timedelay respectively and they are working fine.

[Materials.dmdb.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7473436/Materials.dmdb.zip)
[Abschnitt_3.dflw.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7473439/Abschnitt_3.dflw.zip)
[Abschnitt_4.dflw.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7473440/Abschnitt_4.dflw.zip)
[Abschnitt_3_ohne_zeitversatz.dflw.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7473445/Abschnitt_3_ohne_zeitversatz.dflw.zip)
[Abschnitt_4_ohne_zeitversatz.dflw.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7473447/Abschnitt_4_ohne_zeitversatz.dflw.zip)

**Comment by vasylskorych** [comment]
Should work now in the most recent version. Please try:
[issue44.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7482317/issue44.zip)
