### ISSUE TITLE
Dyssol crashes

### ISSUE THREAD

**Issue by HannesWeska** [FlowsheetSimulation/Dyssol-open#51]
If the End siumlation time is larger than certain value Dyssol crashes. The Model was tested on two different devices. With one PC 60 s was the max value, 100 s with the other one.
After Dyssol is closed the fault report in the Linux-terminal looks like this:
[Materials.dmdb.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7522203/Materials.dmdb.zip)
[anlage_gesamt_nr27_eingang_abschnitt_4.dflw.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7522205/anlage_gesamt_nr27_eingang_abschnitt_4.dflw.zip)
 End siumlation time 100 s:
„terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot get file size: No such file or directory [/home/hannesweska/.config/Dyssol/cache/MD_Ku108RcTFzQL6gzgcRjh1.cache]
Aborted (core dumped)“
End siumlation time 90 s:
„terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)"
[anlage_gesamt_nr27_eingang_abschnitt_4.dflw.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7522212/anlage_gesamt_nr27_eingang_abschnitt_4.dflw.zip)
[Materials.dmdb.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7522216/Materials.dmdb.zip)

**Comment by vasylskorych** [comment]
- Please check out the newest version - it should be fixed now.
- For this flowsheet, I would suggest to disable caching completely (Setup -> Options -> Service -> Caching), as it considerably slows down the simulation.
- Be aware of changed Delay unit. It now comprises 2 models: prevoius "norm-based", which has some differential equations underneath; and a new "simple-shift" model, which does not change the input signal, but only shifts all input time points by a given value. Check what model works better for you.
