### ISSUE TITLE
wrong mass-flow in bunker output

### ISSUE THREAD

**Issue by HannesWeska** [FlowsheetSimulation/Dyssol-open#54]
If there is a bigger pause between material-inputs to the InletFlow, the following bunker only passes the first input through.
In addition the mass-flow of "Siloabzug Nr 27"(bunker output) doesn't fit to the input of "Sieb Nr 20 >16mm (2)".
[anlage_gesamt_nr27_eingang_abschnitt_4.dflw.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7553870/anlage_gesamt_nr27_eingang_abschnitt_4.dflw.zip)
[Materials.dmdb.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7553874/Materials.dmdb.zip)

**Comment by HannesWeska** [comment]
I was talking about the stream Bunkerabzug Nr 2 compared to Eingangsmassenstrom.

**Comment by vasylskorych** [comment]
Both problems should be fixed with #57. The silo should now respond to all changes in the input signals, regardless of their frequency. This has implications for a given flowsheet in a drastically increased number of generated time points.
